import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ShieldCheck, ExternalLink } from 'lucide-react';
import { SeverityBadge, ProtocolBadge } from './Badge';
import { useSecurity } from '../../context/SecurityContext';
export const InvestigateModal: React.FC = () => {
  const { inspectThreatModal, setInspectThreatModal, navigateToIp } = useSecurity();
  const threat = inspectThreatModal;
  if (!threat) return null;
  return <AnimatePresence><div className="fixed inset-0 z-50 flex items-center justify-center p-4"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setInspectThreatModal(null)} className="absolute inset-0 bg-black/60 backdrop-blur-sm"/><motion.div initial={{opacity:0,y:10,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.98}} className="relative z-10 w-full max-w-2xl max-h-[85vh] overflow-hidden rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl"><div className="p-5 border-b flex items-center justify-between"><div><div className="flex items-center gap-2"><h3 className="font-bold">{threat.threatType}</h3><SeverityBadge severity={threat.severity}/></div><p className="text-xs text-slate-500 mt-1">Passive detection evidence</p></div><button onClick={()=>setInspectThreatModal(null)}><X className="w-5 h-5 text-slate-400"/></button></div><div className="p-5 overflow-y-auto space-y-5 text-xs"><div className="grid sm:grid-cols-2 gap-3"><div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-950/50"><span className="text-slate-500">Source</span><button onClick={()=>navigateToIp(threat.sourceIp)} className="block font-mono mt-1 text-blue-500">{threat.sourceIp} <ExternalLink className="inline w-3 h-3"/></button></div><div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-950/50"><span className="text-slate-500">Destination</span><b className="block font-mono mt-1">{threat.destinationIp}</b></div><div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-950/50"><span className="text-slate-500">Protocol</span><div className="mt-1"><ProtocolBadge protocol={threat.protocol}/></div></div><div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-950/50"><span className="text-slate-500">Detector confidence</span><b className="block font-mono mt-1">{(threat.confidence*100).toFixed(1)}%</b></div></div><div><h4 className="font-bold mb-2">Supporting evidence</h4><div className="space-y-2">{Object.entries(threat.evidence||{}).map(([k,v])=><div key={k} className="flex justify-between gap-4 p-3 rounded-lg border border-slate-200 dark:border-slate-800"><span className="text-slate-500">{k.replaceAll('_',' ')}</span><b className="text-right break-all">{typeof v==='object'?JSON.stringify(v):String(v)}</b></div>)}{!Object.keys(threat.evidence||{}).length&&<div className="text-slate-500">No evidence fields were supplied.</div>}</div></div><div className="p-3 rounded-lg border border-blue-500/30 bg-blue-500/5 text-blue-600 dark:text-blue-300 flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/> Sentinel is analytical and read-only: this view does not issue probes, blocks, quarantine commands, or payload decryption.</div></div></motion.div></div></AnimatePresence>;
};
